[environment]
GROUP_CHAT = "-5177645602"
TIMEZONE = "Europe/Moscow"

[variable.BOT_TOKEN]
value = "8773213233:AAEXOvqK262uaA8_AsMz3JOC3-d53sC5LtE"

[variable.GROUP_CHAT_ID]
value = "-5177645602"

[variable.ADMIN_IDS]
value = "123456789"

[variable.TIMEZONE]
value = "Europe/Moscow"